### ISSUE TITLE
Boundary Parcels

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#34]
"boundary parcels" should include parcels that intersect the boundary of any GSA regulated basin, including parcels that are partially within a GSA basin and the remainder is outside of all other GSA basins.   Code identifies "boundary parcels" as only those that overlap two GSA regulated basins (which is a small subset of boundary parcels)

Code also does not write: 
    GSA_Jurisdiction_Modified = NA,
    GSA_Jurisdiction_Mod_Value = NA,
    GSA_Jurisdiction = NA

These should be coded similar to below.

ppet <- ppet %>% 
  mutate(Ag_GW_Use_Modified       = "No",
         Ag_GW_Use_Modified_Ac_Ft = NA,
         Ag_GW_Use_Comment        = NA,
         Ag_GW_Use_Ac_Ft = ifelse(Ag_GW_Use_Modified == "Yes", 
                                  Ag_GW_Use_Modified_Ac_Ft, 
                                  Ag_GW_Use_GIS_Ac_Ft))

**Comment by andyrich** [comment]
We will use the following spreadsheets to import the modfied values:
![image](https://user-images.githubusercontent.com/16653125/165826703-a6c5885a-04e5-4226-8641-7b50d5083610.png)

They have the following structure:
![image](https://user-images.githubusercontent.com/16653125/165826893-42b0d87d-9355-4a27-b2b1-ea6ddf5d5f1b.png)

The tables will belong in the following folder:

general\modified_values

**Comment by andyrich** [comment]
Not going to implement this. Identifying parcels that overlap multiple basins seems more important than identifying parcels that overlap the edge of any basin. Such an analysis can be performed in GIS if needed.

**Comment by andyrich** [comment]
"boundary parcels" should include parcels that intersect the boundary of any GSA regulated basin, including parcels that are partially within a GSA basin and the remainder is outside of all other GSA basins. Code identifies "boundary parcels" as only those that overlap two GSA regulated basins (which is a small subset of boundary parcels)

This is important because the location of the well (not the parcel intersect) determines the if a parcel pays a fee. There are thousands of parcels along the boundaries that may or not need to pay a fee depending on the location of their well. The code assumes the well is within the basin, but it very well may not be.

The GUIDE survey is setup to take "Basin_Boundary_Parcel" = YES, and ask for more info including a map with the well marked.

**Comment by andyrich** [comment]
begrudged!!

**Comment by robertopennington** [comment]
If this would take a bunch of time to figure out in R, we could have GIS export a list of parcels that intersect the boundary, then import that list to apply to the field?

**Comment by andyrich** [comment]
haha it's all good. i figured it out. preferable to have things all coming same data sources.
