### ISSUE TITLE
Move LandSizeParcelAcres to end of csv export

### ISSUE THREAD

**Issue by robertopennington** [andyrich/gfs_scwa#42]
In order to no mess up Shelly's code, please tack LandSizeParcelAcres onto the end of the csv for PRMD.

Also, looks like there are lots of zeros in the current output for LandSizeParcels.

**Comment by andyrich** [comment]
# For the zeros issue:
The underlying database is the issue:
![image](https://user-images.githubusercontent.com/16653125/166336149-ba640beb-1694-47fd-a3ad-1cc690d3af08.png)

![image](https://user-images.githubusercontent.com/16653125/166336181-a11382ad-d275-4149-ad45-8d6692fb6944.png)

For this portion of the database, the info comes from

`   # parcels from public sonoma county data portal

    # https://gis-sonomacounty.hub.arcgis.com/pages/data
    area <- st_read(path(data_path, "general/parcel/CDR_PARCEL_PUB_SHP_vw.shp") ) %>%`

**Comment by andyrich** [comment]
![image](https://user-images.githubusercontent.com/16653125/166509309-791c069d-882c-4d56-bde9-e828b8dee6f7.png)

![image](https://user-images.githubusercontent.com/16653125/166509357-ca53619a-f10e-450f-9df9-77dde539fc6e.png)


# Note 
Parcel areas are based off geometry of polygon referenced above, and not the Parcel database reported value. This is because the parcel record parcel areas are full of zero's throughout.

**Comment by robertopennington** [comment]
Thanks Andy, annoying the database is full of zeros
