### ISSUE TITLE
parcel size cleanup

### ISSUE THREAD

**Issue by andyrich** [andyrich/gfs_scwa#60]
fix issue #33 and #36

**Comment by andyrich** [comment]
see the following for updated parcel boundary calculations and areas:
https://andyrich.github.io/water_use/boundary_parcels.html

**Comment by andyrich** [comment]
These are 3 parcel area parameters output by the code along with their given definitions:
```
Name -	Definition
LandSizeAcres -	Area of Parcel In basin
LandSizeParcelAcres	- Area of Entire Parcel
Intersect_GSA_Bndry_Sum_Acres -	Combined area that overlaps SRP, Petaluma Valley and Sonoma Valley basins
```

Can you please rename/rearrange the parameters so that they match up with how you want them outputted?

**Comment by robertopennington** [comment]
Name  -	PRMD Name    -      Definition
LandSizeAcres = LandSize_Ac  Area of Entire Parcel	
LandSizeParcelAcres - NaN - do not export to PRMD csv
Intersect_GSA_Bndry_Sum_Acres  -  Intersect_GSA_Bndry_Sum_Ac   -	Area of Parcel In basin

**Comment by andyrich** [comment]
I’m not sure what this means. Do you want me to change the name of Intersect_GSA_Bndry_Sum_Ac to Intersect_GSA_Bndry_Sum_Acres?

**Comment by robertopennington** [comment]
Sorry, that is confusing.  Leave the name as "Intersect_GSA_Bndry_Sum_Ac" in the csv you export for PRMD.  

"PRMD Name" is intended to be the field name used in the PRMD csv.  Since our schema is not consistent, I was trying to make clear what the column in the PRMD csv should represent.

LandSize_Ac =  Area of Entire Parcel
LandSizeParcelAcres - NaN - do not export to PRMD csv
Intersect_GSA_Bndry_Sum_Ac - Area of parcel In basin that intersects the largest fraction of the parcel

**Comment by andyrich** [comment]
I just uploaded the output to the PRMD portal.
